[package]
name = "rust-node"
version = "0.1.0"
authors = ["Brendan Ball"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type=["cdylib"]

[dependencies]
nodejs-sys = "0.4.0"